jenkins:
  systemMessage: "Hello! Welcome to my Jenkins instance :)"
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "admin"
      - id: "jigglypuff"
        password: "password"
        name: "Jigglypuff"
        properties:
        - mailer:
            emailAddress: "jigglypuff@"
jobs:
  - url: "https://raw.githubusercontent.com/EpitechIT2020/T-DOP-600-LYN-6-1-bsmymarvin-gillian.bruyas/master/job_dsl.groovy?token=AKV3KIYOTOFAVKJFA25B2QDAOHZAK"
